#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not govern POSIX, you may need to use bash or ksh.
#
#   (2) Put the GRADLE_HOME environment variable in your environment.
#
#   (3) You may want to put a dot (.) in your path so that you can run gradle
#       by just typing the task name in the directory where the build file is.
#       But Gradle also supports GRADLE_HOME variable for convenience, so you
#       may also run gradle by typing a fully qualified path, like:
#
#           /path/to/org.gradle/gradle/bin/gradle <task>
#
#   or if you add GRADLE_HOME in your environment, by typing:
#
#           gradle <task>
#
#   More details at https://gradle.org/install
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}      # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]                          # test whether app_path is a symbolic link
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}                          # drops all text up to the arrow
    ushlink=$( cd -P "$(dirname "$link")" > /dev/null && pwd -P )"/$link"
    app_path=$( cd -P "$(dirname "$app_path")" > /dev/null && pwd -P )"/$ushlink"
done

APP_HOME=$( cd -P "$(dirname "$APP_HOME")" > /dev/null && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME}" && pwd -P ) || exit 1

# Add a user-defined _JAVA_OPTIONS to the JVM arguments
# See GRADLE_OPTS documentation for other options

DEFAULT_JVM_OPTS='"-Xmx2G" "-Xms512m"'

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
